# Exploratory Data Analysis

In [84]:
import pandas as pd
import numpy as np
from pymongo import MongoClient

### Configuração Inicial

In [85]:
%run pymongo-crud-ingestion.ipynb

c:\Users\laura\anaconda\Lib\site-packages\nbformat\__init__.py:96: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)

299288
Connected to MongoDB
299288
299288
[{'_id': ObjectId('6a1e259b404be8594a9b7d66'), 'Unnamed: 0': 0.0, 'age': 73.0, 'class_of_worker': nan, 'detailed_industry_recode': 0.0, 'detailed_occupation_recode': 0.0, 'education': 'high_school_graduate', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'widowed', 'major_industry_code': 'not_in_universe_or_children', 'major_occupation_code': nan, 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'not_in_labor_force', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'nonfiler', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'other_rel_18+_ever_marr_not_in_subfamily', 'detailed_household_summary_in_household': 'other_relative_of_householder', 'instance_weight': 1700.09, 'migration_code_change_in_msa': nan, 'migration_code_change_in_reg': nan, 'migration_code_move_within_reg': nan, 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 0.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 0.0, 'year': 95.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d67'), 'Unnamed: 0': 1.0, 'age': 58.0, 'class_of_worker': 'self_employed_not_incorporated', 'detailed_industry_recode': 4.0, 'detailed_occupation_recode': 34.0, 'education': 'some_college_but_no_degree', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'divorced', 'major_industry_code': 'construction', 'major_occupation_code': 'precision_production_craft_&_repair', 'race': 'white', 'hispanic_origin': 'all_other', 'sex': nan, 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'children_or_armed_forces', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'head_of_household', 'region_of_previous_residence': 'south', 'state_of_previous_residence': 'arkansas', 'detailed_household_and_family_stat': 'householder', 'detailed_household_summary_in_household': 'householder', 'instance_weight': 1053.55, 'migration_code_change_in_msa': 'msa_to_msa', 'migration_code_change_in_reg': 'same_county', 'migration_code_move_within_reg': 'same_county', 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': 'yes', 'num_persons_worked_for_employer': 1.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 52.0, 'year': 94.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d68'), 'Unnamed: 0': 2.0, 'age': 18.0, 'class_of_worker': nan, 'detailed_industry_recode': 0.0, 'detailed_occupation_recode': 0.0, 'education': '10th_grade', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': 'high_school', 'marital_stat': 'never_married', 'major_industry_code': 'not_in_universe_or_children', 'major_occupation_code': nan, 'race': 'asian_or_pacific_islander', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'not_in_labor_force', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'nonfiler', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'child_18+_never_marr_not_in_a_subfamily', 'detailed_household_summary_in_household': 'child_18_or_older', 'instance_weight': 991.95, 'migration_code_change_in_msa': nan, 'migration_code_change_in_reg': nan, 'migration_code_move_within_reg': nan, 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 0.0, 'family_members_under_18': nan, 'country_of_birth_father': 'vietnam', 'country_of_birth_mother': 'vietnam', 'country_of_birth_self': 'vietnam', 'citizenship': 'foreign_born_not_a_citizen_of_u_s', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 0.0, 'year': 95.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d69'), 'Unnamed: 0': 3.0, 'age': 9.0, 'class_of_worker': nan, 'detailed_industry_recode': 0.0, 'detailed_occupation_recode': 0.0, 'education': 'children', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'never_married', 'major_industry_code': 'not_in_universe_or_children', 'major_occupation_code': nan, 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'children_or_armed_forces', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'nonfiler', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'child_<18_never_marr_not_in_subfamily', 'detailed_household_summary_in_household': 'child_under_18_never_married', 'instance_weight': 1758.14, 'migration_code_change_in_msa': 'nonmover', 'migration_code_change_in_reg': 'nonmover', 'migration_code_move_within_reg': 'nonmover', 'live_in_this_house_1_year_ago': 'yes', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 0.0, 'family_members_under_18': 'both_parents_present', 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 0.0, 'weeks_worked_in_year': 0.0, 'year': 94.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6a'), 'Unnamed: 0': 4.0, 'age': 10.0, 'class_of_worker': nan, 'detailed_industry_recode': 0.0, 'detailed_occupation_recode': 0.0, 'education': 'children', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': nan, 'major_industry_code': nan, 'major_occupation_code': nan, 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'children_or_armed_forces', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'nonfiler', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'child_<18_never_marr_not_in_subfamily', 'detailed_household_summary_in_household': 'child_under_18_never_married', 'instance_weight': 1069.16, 'migration_code_change_in_msa': 'nonmover', 'migration_code_change_in_reg': 'nonmover', 'migration_code_move_within_reg': 'nonmover', 'live_in_this_house_1_year_ago': 'yes', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 0.0, 'family_members_under_18': 'both_parents_present', 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 0.0, 'weeks_worked_in_year': 0.0, 'year': 94.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6b'), 'Unnamed: 0': 5.0, 'age': 48.0, 'class_of_worker': 'private', 'detailed_industry_recode': 40.0, 'detailed_occupation_recode': 10.0, 'education': 'some_college_but_no_degree', 'wage_per_hour': 1200.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'married_civilian_spouse_present', 'major_industry_code': 'entertainment', 'major_occupation_code': 'professional_specialty', 'race': 'amer_indian_aleut_or_eskimo', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': 'no', 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'full_time_schedules', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'joint_both_under_65', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'spouse_of_householder', 'detailed_household_summary_in_household': 'spouse_of_householder', 'instance_weight': 162.61, 'migration_code_change_in_msa': nan, 'migration_code_change_in_reg': nan, 'migration_code_move_within_reg': nan, 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 1.0, 'family_members_under_18': nan, 'country_of_birth_father': 'philippines', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 2.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 52.0, 'year': 95.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6c'), 'Unnamed: 0': 6.0, 'age': 42.0, 'class_of_worker': 'private', 'detailed_industry_recode': 34.0, 'detailed_occupation_recode': 3.0, 'education': 'bachelors_degree(ba_ab_bs)', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'married_civilian_spouse_present', 'major_industry_code': 'finance_insurance_and_real_estate', 'major_occupation_code': 'executive_admin_and_managerial', 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'male', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'children_or_armed_forces', 'capital_gains': 5178.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'joint_both_under_65', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'householder', 'detailed_household_summary_in_household': 'householder', 'instance_weight': 1535.86, 'migration_code_change_in_msa': 'nonmover', 'migration_code_change_in_reg': 'nonmover', 'migration_code_move_within_reg': 'nonmover', 'live_in_this_house_1_year_ago': 'yes', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 6.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 52.0, 'year': 94.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6d'), 'Unnamed: 0': 7.0, 'age': 28.0, 'class_of_worker': 'private', 'detailed_industry_recode': 4.0, 'detailed_occupation_recode': 40.0, 'education': 'high_school_graduate', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'never_married', 'major_industry_code': 'construction', 'major_occupation_code': 'handlers_equip_cleaners_etc', 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': nan, 'reason_for_unemployment': 'job_loser_on_layoff', 'full_or_part_time_employment_stat': 'unemployed_full_time', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'single', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'secondary_individual', 'detailed_household_summary_in_household': 'nonrelative_of_householder', 'instance_weight': 898.83, 'migration_code_change_in_msa': nan, 'migration_code_change_in_reg': nan, 'migration_code_move_within_reg': nan, 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 4.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 30.0, 'year': 95.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6e'), 'Unnamed: 0': 8.0, 'age': 47.0, 'class_of_worker': 'local_government', 'detailed_industry_recode': 43.0, 'detailed_occupation_recode': 26.0, 'education': 'some_college_but_no_degree', 'wage_per_hour': 876.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': 'married_civilian_spouse_present', 'major_industry_code': 'education', 'major_occupation_code': 'adm_support_including_clerical', 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'female', 'member_of_a_labor_union': 'no', 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'full_time_schedules', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'joint_both_under_65', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'spouse_of_householder', 'detailed_household_summary_in_household': 'spouse_of_householder', 'instance_weight': 1661.53, 'migration_code_change_in_msa': nan, 'migration_code_change_in_reg': nan, 'migration_code_move_within_reg': nan, 'live_in_this_house_1_year_ago': 'no', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 5.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 52.0, 'year': 95.0, 'income': '<=50000', 'source_split': 'train'}, {'_id': ObjectId('6a1e259b404be8594a9b7d6f'), 'Unnamed: 0': 9.0, 'age': 34.0, 'class_of_worker': 'private', 'detailed_industry_recode': 4.0, 'detailed_occupation_recode': 37.0, 'education': 'some_college_but_no_degree', 'wage_per_hour': 0.0, 'enroll_in_edu_inst_last_wk': nan, 'marital_stat': nan, 'major_industry_code': 'construction', 'major_occupation_code': 'machine_operators_assmblrs_&_inspctrs', 'race': 'white', 'hispanic_origin': 'all_other', 'sex': 'male', 'member_of_a_labor_union': nan, 'reason_for_unemployment': nan, 'full_or_part_time_employment_stat': 'children_or_armed_forces', 'capital_gains': 0.0, 'capital_losses': 0.0, 'dividends_from_stocks': 0.0, 'tax_filer_stat': 'joint_both_under_65', 'region_of_previous_residence': nan, 'state_of_previous_residence': nan, 'detailed_household_and_family_stat': 'householder', 'detailed_household_summary_in_household': 'householder', 'instance_weight': 1146.79, 'migration_code_change_in_msa': 'nonmover', 'migration_code_change_in_reg': 'nonmover', 'migration_code_move_within_reg': 'nonmover', 'live_in_this_house_1_year_ago': 'yes', 'migration_prev_res_in_sunbelt': nan, 'num_persons_worked_for_employer': 6.0, 'family_members_under_18': nan, 'country_of_birth_father': 'united_states', 'country_of_birth_mother': 'united_states', 'country_of_birth_self': 'united_states', 'citizenship': 'native_born_in_the_united_states', 'own_business_or_self_employed': 0.0, 'fill_inc_questionnaire_for_veteran_admin': nan, 'veterans_benefits': 2.0, 'weeks_worked_in_year': 52.0, 'year': 94.0, 'income': '<=50000', 'source_split': 'train'}]
299288

In [86]:
MONGO_CONFIG = {
    "user": "labuser",
    "password": "labpass",
    "host": "localhost",
    "port": 27017,
    "database": "census_income_kdd"
}

RAW_DIR = '../raw/clean'
COLLECTION_NAME = 'census'

In [87]:
db_manager = MongoDatabase(MONGO_CONFIG)
db = db_manager.connect()

In [88]:
executor = MongoExecutor(db, COLLECTION_NAME)
df = pd.DataFrame(executor.select({},limit=0))

In [89]:
print(f'Total documents: {executor.count_documents({})}')

Total documents: 299288

### Análise do DataFrame

In [90]:
df.shape

(299288, 45)

In [91]:
df.columns

Index(['_id', 'Unnamed: 0', 'age', 'class_of_worker',
       'detailed_industry_recode', 'detailed_occupation_recode', 'education',
       'wage_per_hour', 'enroll_in_edu_inst_last_wk', 'marital_stat',
       'major_industry_code', 'major_occupation_code', 'race',
       'hispanic_origin', 'sex', 'member_of_a_labor_union',
       'reason_for_unemployment', 'full_or_part_time_employment_stat',
       'capital_gains', 'capital_losses', 'dividends_from_stocks',
       'tax_filer_stat', 'region_of_previous_residence',
       'state_of_previous_residence', 'detailed_household_and_family_stat',
       'detailed_household_summary_in_household', 'instance_weight',
       'migration_code_change_in_msa', 'migration_code_change_in_reg',
       'migration_code_move_within_reg', 'live_in_this_house_1_year_ago',
       'migration_prev_res_in_sunbelt', 'num_persons_worked_for_employer',
       'family_members_under_18', 'country_of_birth_father',
       'country_of_birth_mother', 'country_of_birth_self', 'citizenship',
       'own_business_or_self_employed',
       'fill_inc_questionnaire_for_veteran_admin', 'veterans_benefits',
       'weeks_worked_in_year', 'year', 'income', 'source_split'],
      dtype='str')

In [92]:
df = df.drop(columns=['_id', 'Unnamed: 0'])

In [93]:
df.head()

,age,class_of_worker,detailed_industry_recode,detailed_occupation_recode,education,wage_per_hour,enroll_in_edu_inst_last_wk,marital_stat,major_industry_code,major_occupation_code,...,country_of_birth_mother,country_of_birth_self,citizenship,own_business_or_self_employed,fill_inc_questionnaire_for_veteran_admin,veterans_benefits,weeks_worked_in_year,year,income,source_split
0,73.0,NaN,0.0,0.0,high_school_graduate,0.0,NaN,widowed,not_in_universe_or_children,NaN,...,united_states,united_states,native_born_in_the_united_states,0.0,NaN,2.0,0.0,95.0,<=50000,train
1,58.0,self_employed_not_incorporated,4.0,34.0,some_college_but_no_degree,0.0,NaN,divorced,construction,precision_production_craft_&_repair,...,united_states,united_states,native_born_in_the_united_states,0.0,NaN,2.0,52.0,94.0,<=50000,train
2,18.0,NaN,0.0,0.0,10th_grade,0.0,high_school,never_married,not_in_universe_or_children,NaN,...,vietnam,vietnam,foreign_born_not_a_citizen_of_u_s,0.0,NaN,2.0,0.0,95.0,<=50000,train
3,9.0,NaN,0.0,0.0,children,0.0,NaN,never_married,not_in_universe_or_children,NaN,...,united_states,united_states,native_born_in_the_united_states,0.0,NaN,0.0,0.0,94.0,<=50000,train
4,10.0,NaN,0.0,0.0,children,0.0,NaN,NaN,NaN,NaN,...,united_states,united_states,native_born_in_the_united_states,0.0,NaN,0.0,0.0,94.0,<=50000,train

In [115]:
df.duplicated().sum()

np.int64(2192)

In [94]:
df = df.drop_duplicates()

In [ ]:
df.shape

TypeError: 'tuple' object is not callable

### Missing values

In [95]:
((df.isna().sum())/len(df)*100).sort_values(ascending=False)

fill_inc_questionnaire_for_veteran_admin    98.985163
reason_for_unemployment                     96.963579
enroll_in_edu_inst_last_wk                  93.637975
state_of_previous_residence                 92.449899
region_of_previous_residence                92.100048
migration_prev_res_in_sunbelt               92.100048
member_of_a_labor_union                     90.380454
family_members_under_18                     72.996111
class_of_worker                             50.795759
migration_code_change_in_reg                50.710487
migration_code_move_within_reg              50.710487
migration_code_change_in_msa                50.710487
major_occupation_code                       50.013819
country_of_birth_father                      3.415931
country_of_birth_mother                      3.095066
age                                          2.387276
income                                       2.017203
tax_filer_stat                               2.017203
citizenship                                  2.017203
detailed_industry_recode                     2.016866
major_industry_code                          2.016866
source_split                                 2.016529
sex                                          2.016529
race                                         2.016529
education                                    2.015855
marital_stat                                 2.015855
country_of_birth_self                        1.737120
weeks_worked_in_year                         0.378162
wage_per_hour                                0.378162
capital_gains                                0.378162
detailed_occupation_recode                   0.000000
hispanic_origin                              0.000000
full_or_part_time_employment_stat            0.000000
capital_losses                               0.000000
dividends_from_stocks                        0.000000
detailed_household_summary_in_household      0.000000
instance_weight                              0.000000
detailed_household_and_family_stat           0.000000
num_persons_worked_for_employer              0.000000
live_in_this_house_1_year_ago                0.000000
own_business_or_self_employed                0.000000
veterans_benefits                            0.000000
year                                         0.000000
dtype: float64

In [96]:
#Colunas com mais de 50% de valores nulos
df = df.drop(columns=['fill_inc_questionnaire_for_veteran_admin','reason_for_unemployment','enroll_in_edu_inst_last_wk','state_of_previous_residence','region_of_previous_residence','migration_prev_res_in_sunbelt','member_of_a_labor_union','family_members_under_18','class_of_worker','migration_code_change_in_reg','migration_code_move_within_reg','migration_code_change_in_msa','major_occupation_code'])

In [97]:
((df.select_dtypes('number').isna().sum())/len(df)*100).sort_values(ascending=False)

age                                2.387276
detailed_industry_recode           2.016866
wage_per_hour                      0.378162
capital_gains                      0.378162
weeks_worked_in_year               0.378162
detailed_occupation_recode         0.000000
capital_losses                     0.000000
instance_weight                    0.000000
dividends_from_stocks              0.000000
num_persons_worked_for_employer    0.000000
own_business_or_self_employed      0.000000
veterans_benefits                  0.000000
year                               0.000000
dtype: float64

In [98]:
for col in df.select_dtypes('number').columns:
    df[col] = df[col].fillna(df[col].median())

In [99]:
((df.isna().sum())/len(df)*100).sort_values(ascending=False)

country_of_birth_father                    3.415931
country_of_birth_mother                    3.095066
citizenship                                2.017203
tax_filer_stat                             2.017203
income                                     2.017203
major_industry_code                        2.016866
sex                                        2.016529
race                                       2.016529
source_split                               2.016529
marital_stat                               2.015855
education                                  2.015855
country_of_birth_self                      1.737120
wage_per_hour                              0.000000
detailed_industry_recode                   0.000000
dividends_from_stocks                      0.000000
capital_losses                             0.000000
capital_gains                              0.000000
full_or_part_time_employment_stat          0.000000
hispanic_origin                            0.000000
age                                        0.000000
detailed_occupation_recode                 0.000000
detailed_household_and_family_stat         0.000000
live_in_this_house_1_year_ago              0.000000
num_persons_worked_for_employer            0.000000
detailed_household_summary_in_household    0.000000
instance_weight                            0.000000
veterans_benefits                          0.000000
own_business_or_self_employed              0.000000
year                                       0.000000
weeks_worked_in_year                       0.000000
dtype: float64

In [112]:
for col in df.select_dtypes('str').columns:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

In [114]:
((df.isna().sum())/len(df)*100).sort_values(ascending=False)

age                                        0.0
detailed_industry_recode                   0.0
detailed_occupation_recode                 0.0
education                                  0.0
wage_per_hour                              0.0
marital_stat                               0.0
major_industry_code                        0.0
race                                       0.0
hispanic_origin                            0.0
sex                                        0.0
full_or_part_time_employment_stat          0.0
capital_gains                              0.0
capital_losses                             0.0
dividends_from_stocks                      0.0
tax_filer_stat                             0.0
detailed_household_and_family_stat         0.0
detailed_household_summary_in_household    0.0
instance_weight                            0.0
live_in_this_house_1_year_ago              0.0
num_persons_worked_for_employer            0.0
country_of_birth_father                    0.0
country_of_birth_mother                    0.0
country_of_birth_self                      0.0
citizenship                                0.0
own_business_or_self_employed              0.0
veterans_benefits                          0.0
weeks_worked_in_year                       0.0
year                                       0.0
income                                     0.0
source_split                               0.0
dtype: float64

In [117]:
df.describe()

,age,detailed_industry_recode,detailed_occupation_recode,wage_per_hour,capital_gains,capital_losses,dividends_from_stocks,instance_weight,num_persons_worked_for_employer,own_business_or_self_employed,veterans_benefits,weeks_worked_in_year,year
count,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000,296698.000000
mean,34.738586,15.171693,11.412345,55.369261,433.434998,37.170308,197.555289,1741.799786,1.973134,0.177986,1.528959,23.330747,94.506377
std,22.008835,18.024323,14.479632,274.060584,4678.994466,270.941373,1946.189882,995.814467,2.368042,0.557390,0.842649,24.382315,3.588339
min,-2.000000,0.000000,0.000000,-100.000000,0.000000,0.000000,0.000000,37.870000,0.000000,0.000000,0.000000,0.000000,94.000000
25%,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1060.600000,0.000000,0.000000,2.000000,0.000000,94.000000
50%,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1618.510000,1.000000,0.000000,2.000000,10.000000,94.000000
75%,49.000000,33.000000,26.000000,0.000000,0.000000,0.000000,0.000000,2191.527500,4.000000,0.000000,2.000000,52.000000,95.000000
max,150.000000,51.000000,46.000000,9999.000000,99999.000000,4608.000000,99999.000000,18656.300000,6.000000,2.000000,2.000000,80.000000,2030.000000

In [119]:
df.age.unique()

array([ 73.,  58.,  18.,   9.,  10.,  48.,  42.,  28.,  47.,  34.,   8.,
        32.,  51.,  46.,  26.,  13.,  39.,  16.,  35.,  12.,  27.,  56.,
        55.,   2.,   1.,  37.,   4.,  63.,  25.,  81.,  11.,  30.,   7.,
        66.,  84.,  52.,   5.,  36.,  72.,  61.,  41.,  90.,  49.,   6.,
         0.,  33.,  57.,  50.,  24.,  53.,  40.,  54.,  22.,  29.,  85.,
        38.,  76.,  21.,  31.,  74.,  19.,  15.,   3.,  43.,  68.,  71.,
        45.,  62.,  23.,  69.,  75.,  44.,  17.,  59.,  60.,  64.,  65.,
        70.,  67.,  78.,  20.,  14.,  83.,  86.,  89.,  77.,  79.,  82.,
        80.,  87.,  88.,  -2., 150.])

In [128]:
df.loc[df['age']==-2, 'age']=0
df = df.drop(index = df.loc[df['age']==150].index)

In [129]:
df.describe()

,age,detailed_industry_recode,detailed_occupation_recode,wage_per_hour,capital_gains,capital_losses,dividends_from_stocks,instance_weight,num_persons_worked_for_employer,own_business_or_self_employed,veterans_benefits,weeks_worked_in_year,year
count,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000,296697.000000
mean,34.738204,15.171731,11.412269,55.369448,433.436459,37.170433,197.555954,1741.800513,1.973138,0.177986,1.528961,23.330650,94.506375
std,22.007844,18.024342,14.479598,274.061027,4679.002284,270.941821,1946.193128,995.816066,2.368045,0.557391,0.842649,24.382299,3.588345
min,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000,0.000000,37.870000,0.000000,0.000000,0.000000,0.000000,94.000000
25%,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1060.600000,0.000000,0.000000,2.000000,0.000000,94.000000
50%,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1618.510000,1.000000,0.000000,2.000000,10.000000,94.000000
75%,49.000000,33.000000,26.000000,0.000000,0.000000,0.000000,0.000000,2191.530000,4.000000,0.000000,2.000000,52.000000,95.000000
max,90.000000,51.000000,46.000000,9999.000000,99999.000000,4608.000000,99999.000000,18656.300000,6.000000,2.000000,2.000000,80.000000,2030.000000

In [130]:
df.head()

,age,detailed_industry_recode,detailed_occupation_recode,education,wage_per_hour,marital_stat,major_industry_code,race,hispanic_origin,sex,...,country_of_birth_father,country_of_birth_mother,country_of_birth_self,citizenship,own_business_or_self_employed,veterans_benefits,weeks_worked_in_year,year,income,source_split
0,73.0,0.0,0.0,high_school_graduate,0.0,widowed,not_in_universe_or_children,white,all_other,female,...,united_states,united_states,united_states,native_born_in_the_united_states,0.0,2.0,0.0,95.0,<=50000,train
1,58.0,4.0,34.0,some_college_but_no_degree,0.0,divorced,construction,white,all_other,female,...,united_states,united_states,united_states,native_born_in_the_united_states,0.0,2.0,52.0,94.0,<=50000,train
2,18.0,0.0,0.0,10th_grade,0.0,never_married,not_in_universe_or_children,asian_or_pacific_islander,all_other,female,...,vietnam,vietnam,vietnam,foreign_born_not_a_citizen_of_u_s,0.0,2.0,0.0,95.0,<=50000,train
3,9.0,0.0,0.0,children,0.0,never_married,not_in_universe_or_children,white,all_other,female,...,united_states,united_states,united_states,native_born_in_the_united_states,0.0,0.0,0.0,94.0,<=50000,train
4,10.0,0.0,0.0,children,0.0,never_married,not_in_universe_or_children,white,all_other,female,...,united_states,united_states,united_states,native_born_in_the_united_states,0.0,0.0,0.0,94.0,<=50000,train

In [139]:
for col in df.select_dtypes('str').columns:
    if len(df[col].unique()) <= 5:
        print(col)
        print(df[col].unique())
        print()

race
<StringArray>
[                      'white',   'asian_or_pacific_islander',
 'amer_indian_aleut_or_eskimo',                       'black',
                       'other']
Length: 5, dtype: str

sex
<StringArray>
['female', 'male']
Length: 2, dtype: str

live_in_this_house_1_year_ago
<StringArray>
['no', 'yes']
Length: 2, dtype: str

citizenship
<StringArray>
[          'native_born_in_the_united_states',
          'foreign_born_not_a_citizen_of_u_s',
 'foreign_born_u_s_citizen_by_naturalization',
   'native_born_abroad_of_american_parent(s)',
 'native_born_in_puerto_rico_or_u_s_outlying']
Length: 5, dtype: str

income
<StringArray>
['<=50000', 'low_income', '>50000', 'high_income']
Length: 4, dtype: str

source_split
<StringArray>
['train', 'test']
Length: 2, dtype: str